servers:
# MCP servers
  - name: MathServer
    url: http://127.0.0.1:8000/mcp
    use_sandbox: false
    use: true

  - name: UnitServer
    url: http://127.0.0.1:8001/mcp
    use_sandbox: false
    use: true

  - name: OSINTServer
    url: http://127.0.0.1:8002/mcp
    use_sandbox: false
    use: true
  

  # MCP-based Software
  - name: LightSystem
    url: http://127.0.0.1:9000/mcp
    desc: software/LightSystem/desc.json
    use_sandbox: true
    use: true

  - name: LightTalk
    url: http://127.0.0.1:9001/mcp
    desc: software/LightTalk/desc.json
    use_sandbox: true
    use: true

  - name: LightShop
    url: http://127.0.0.1:9002/mcp
    desc: software/LightShop/desc.json
    use_sandbox: true
    use: true
  
  - name: LightWeather
    url: http://127.0.0.1:9003/mcp
    desc: software/LightWeather/desc.json
    use_sandbox: true
    use: true

  - name: LightFlight
    url: http://127.0.0.1:9004/mcp
    desc: software/LightFlight/desc.json
    use_sandbox: true
    use: true

  - name: LightStock
    url: http://127.0.0.1:9005/mcp
    desc: software/LightStock/desc.json
    use_sandbox: true
    use: true
